### PR TITLE
Update maintainers in meta.yaml

### PR DESCRIPTION
**Pull request by erogluorhan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

Hi @kmpaul, I thought you'd want to drop your name, but if you'd like to stay in the maintainers list, I am more than happy to get you back into to it.

### CODE REVIEW

**Comment by kmpaul** [comment]
Thanks, @erogluorhan! It probably best to remove my name.

**Comment by erogluorhan** [comment]
Sounds good, thanks  @kmpaul ! Once you have a chance to review it, we can move this forward then. Best,

**Review by dopplershift — APPROVED** [review]
Merging as another Pythia contributor.

**Comment by erogluorhan** [comment]
Thanks a lot!

**Pull request merged**
